In [ ]:
API_TOKEN_MONDAY_COM = "eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjYzNTg3MDI0NywiYWFpIjoxMSwidWlkIjoxMDEyMTQzNDgsImlhZCI6IjIwMjYtMDMtMjBUMTk6MDI6MTYuMzYzWiIsInBlciI6Im1lOndyaXRlIiwiYWN0aWQiOjM0MzA2ODU0LCJyZ24iOiJhcHNlMiJ9.BfnuqriGTwb8n4JXjC4NtMdTa2qSyTxGqz0WO5VKce0"

In [1]:
import pandas as pd

In [2]:
deal_funnel_data = pd.read_excel("F:\PyTorch_GPU\Agentic_Monday_BI\Data_connections\Data\Deal funnel Data.xlsx")
deal_funnel_data.head()

,Deal Name,Owner code,Client Code,Deal Status,Close Date (A),Closure Probability,Masked Deal value,Tentative Close Date,Deal Stage,Product deal,Sector/service,Created Date
0,Naruto,OWNER_001,COMPANY089,Open,NaN,High,489360.0,2026-02-26 00:00:00,B. Sales Qualified Leads,Service + Spectra,Mining,2025-12-26 00:00:00
1,Sasuke,OWNER_001,COMPANY091,Open,NaN,NaN,17616960.0,2026-02-28 00:00:00,B. Sales Qualified Leads,NaN,Mining,2025-09-15 00:00:00
2,Sasuke,OWNER_002,COMPANY124,Open,NaN,Medium,611700.0,2026-02-26 00:00:00,E. Proposal/Commercials Sent,NaN,Powerline,2025-11-12 00:00:00
3,Sakura,OWNER_002,COMPANY046,Open,NaN,Low,2348928.0,2026-03-20 00:00:00,E. Proposal/Commercials Sent,NaN,Powerline,2025-10-14 00:00:00
4,Sakura,OWNER_002,COMPANY148,Open,NaN,High,428190.0,2026-02-26 00:00:00,E. Proposal/Commercials Sent,NaN,Powerline,2025-10-10 00:00:00

In [4]:
deal_funnel_data.columns

Index(['Deal Name', 'Owner code', 'Client Code', 'Deal Status',
       'Close Date (A)', 'Closure Probability', 'Masked Deal value',
       'Tentative Close Date', 'Deal Stage', 'Product deal', 'Sector/service',
       'Created Date'],
      dtype='object')

In [5]:
deal_funnel_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 346 entries, 0 to 345
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Deal Name             344 non-null    object
 1   Owner code            329 non-null    object
 2   Client Code           344 non-null    object
 3   Deal Status           345 non-null    object
 4   Close Date (A)        28 non-null     object
 5   Closure Probability   88 non-null     object
 6   Masked Deal value     165 non-null    float64
 7   Tentative Close Date  272 non-null    object
 8   Deal Stage            346 non-null    object
 9   Product deal          176 non-null    object
 10  Sector/service        338 non-null    object
 11  Created Date          345 non-null    object
dtypes: float64(1), object(11)
memory usage: 32.6+ KB

In [ ]:
deal_funnel_data.describe()

       Masked Deal value
count       1.650000e+02
mean        1.397284e+07
std         6.824868e+07
min         5.144030e+04
25%         3.670200e+05
50%         1.101060e+06
75%         3.988804e+06
max         7.514734e+08

:

In [ ]:
deal_funnel_data['']